#!/usr/bin/env python3
"""
Regression tests for get_structure_props and size distribution pipeline.

This test is NOT expected to last forever. It was written to guard against
regressions during a refactor of get_structure_props for performance
(single-pass O(n) perimeter/area computation). Once the refactor is stable
and validated, this test may be replaced or pruned.

Strategy:
  1. fBm spot-check: hardcoded values at 10 pixel locations per H value detect
     if scaleinvariance.fBm_ND_circulant changes (so we know the *input* is
     stable before blaming objscale).
  2. Recursive fractal exact tests: fractals from test_fractal_dimensions produce
     perfect squares with analytically known area, perimeter, height, width, and
     exact counts per scale. No tolerance needed.
  3. fBm regression: seeded fBm fields at H=0,0.3,0.5,0.7,1 with uniform,
     stretched, and random pixel sizes. Sorted (area, perimeter) arrays are saved
     to .npz reference files and compared exactly.
  4. Size distribution regression: finite_array_size_distribution outputs for
     area and perimeter variables, compared to saved references.

Reference data lives in regression_refs/ and is generated by --regen.
"""

import numpy as np
import sys
import os
import argparse

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
import objscale
import scaleinvariance

# Also import fractal generation from existing test
sys.path.insert(0, os.path.dirname(__file__))
from test_fractal_dimensions import generate_fractal, FRACTAL_SEEDS

# =============================================================================
# Constants
# =============================================================================

REFERENCE_DIR = os.path.join(os.path.dirname(__file__), 'regression_refs')
ARRAY_SIZE = 512
SEED = 12345
H_VALUES = [0.0, 0.3, 0.5, 0.7, 1.0]
THRESHOLD_PERCENTILE = 50
PIXEL_SIZE_CONFIGS = ['uniform', 'stretched', 'random']
RTOL = 0       # no relative tolerance
ATOL = 1e-10   # absolute tolerance for float comparisons

# Hardcoded spot-check values for scaleinvariance fBm_ND_circulant.
# If these fail, the fBm generator changed — not objscale's fault.
FBM_SPOT_PIXEL_LOCS = [
    (50, 50), (100, 200), (200, 100), (256, 256), (300, 150),
    (150, 400), (400, 300), (10, 500), (450, 50), (500, 500),
]
FBM_SPOT_VALUES = {
    0.0: [0.3865606052, 0.3997569164, 1.6815064759, 1.1887247145, -0.2609067002,
          -0.1839263699, -0.0901614496, -1.226375675, -0.166712831, -1.117962443],
    0.3: [-0.1016594327, 1.1793754041, 0.7717794752, 0.5578833826, -0.0544403222,
          -0.0083814918, 0.0611337286, -1.725100794, -0.5246124556, -0.9197088875],
    0.5: [-0.4686960065, 1.4039039021, 0.245797961, 0.2463134526, -0.1301204536,
          0.2025295079, 0.1408970951, -1.6704018436, -0.8182340361, -0.8301707021],
    0.7: [-0.7876389001, 1.4464705018, -0.1405822674, 0.0575632368, -0.2834563444,
          0.4101860388, 0.2152949511, -1.5078798555, -1.0593932092, -0.7862630057],
    1.0: [-1.1476119415, 1.3442239301, -0.5272552941, -0.0776644832, -0.5310025312,
          0.6584960111, 0.3211317028, -1.2682718038, -1.2984032297, -0.7668533634],
}

# Expected exact values for recursive fractal structures.
# {seed_name: {iterations: [(area, perimeter, height, width, count), ...]}}
# All objects are perfect squares: area=s^2, perimeter=4*s, height=s, width=s.
# Count at scale k: n_zeros^k objects at that scale.
# Side length at scale k is seed_size^(iters-1-k) for seeds with single-pixel 1s
# (3x3_center, 5x5_center), or base_side * seed_size^(iters-1-k) for seeds with
# multi-pixel 1-blocks (5x5_block has base_side=3).
FRACTAL_EXACT = {
    '3x3_center': {  # n_zeros=8, seed_size=3
        3: [  # 27x27
            # (area, perimeter, height, width, count)
            (1.0, 4.0, 1.0, 1.0, 64),    # 8^2 = 64 objects of side 1
            (9.0, 12.0, 3.0, 3.0, 8),     # 8^1 = 8 objects of side 3
            (81.0, 36.0, 9.0, 9.0, 1),    # 8^0 = 1 object of side 9
        ],
    },
    '5x5_center': {  # n_zeros=24, seed_size=5
        2: [  # 25x25
            (1.0, 4.0, 1.0, 1.0, 24),     # 24^1 objects of side 1
            (25.0, 20.0, 5.0, 5.0, 1),    # 24^0 objects of side 5
        ],
    },
    '5x5_block': {  # n_zeros=16, seed_size=5
        3: [  # 125x125
            (9.0, 12.0, 3.0, 3.0, 256),   # 16^2 objects of side 3
            (225.0, 60.0, 15.0, 15.0, 16), # 16^1 objects of side 15
            (5625.0, 300.0, 75.0, 75.0, 1), # 16^0 objects of side 75
        ],
    },
}


# =============================================================================
# Helpers
# =============================================================================

def _generate_field(H, pad=True):
    """Generate a reproducible thresholded fBm field.

    Parameters
    ----------
    H : float
        Hurst exponent.
    pad : bool
        If True, encase in zeros (needed for get_structure_props which requires
        a border). If False, return raw binary (for size distribution tests that
        add their own NaN border internally — padding with zeros would hide
        truncated structures from the truncation test path).
    """
    scaleinvariance.set_backend('numpy')
    np.random.seed(SEED)
    field = scaleinvariance.fBm_ND_circulant((ARRAY_SIZE, ARRAY_SIZE), H=H)
    binary = (field > np.percentile(field, THRESHOLD_PERCENTILE)).astype(np.float32)
    if pad:
        binary = objscale.encase_in_value(binary, value=0, dtype=np.float32)
    return binary


def _generate_raw_field(H):
    """Generate a reproducible raw (unthresholded) fBm field."""
    scaleinvariance.set_backend('numpy')
    np.random.seed(SEED)
    return scaleinvariance.fBm_ND_circulant((ARRAY_SIZE, ARRAY_SIZE), H=H)


def _make_sizes(binary, config):
    """Create pixel size arrays for a given config name."""
    if config == 'uniform':
        return np.ones_like(binary, dtype=np.float32), np.ones_like(binary, dtype=np.float32)
    elif config == 'stretched':
        ny, nx = binary.shape
        x_sizes = np.broadcast_to(
            np.linspace(0.5, 2.0, nx, dtype=np.float32)[np.newaxis, :], binary.shape
        ).copy()
        y_sizes = np.broadcast_to(
            np.linspace(0.8, 1.5, ny, dtype=np.float32)[:, np.newaxis], binary.shape
        ).copy()
        return x_sizes, y_sizes
    elif config == 'random':
        np.random.seed(SEED + 2)
        x_sizes = (0.5 + np.random.rand(*binary.shape)).astype(np.float32)
        y_sizes = (0.5 + np.random.rand(*binary.shape)).astype(np.float32)
        return x_sizes, y_sizes
    else:
        raise ValueError(f"Unknown config: {config}")


def _sort_props(p, a):
    """Sort structure properties by (area, perimeter) for order-independent comparison."""
    order = np.lexsort((p, a))
    return p[order], a[order]


# =============================================================================
# Reference data generation
# =============================================================================

def generate_reference_data():
    """Generate and save all reference data to regression_refs/."""
    os.makedirs(REFERENCE_DIR, exist_ok=True)

    for H in H_VALUES:
        binary = _generate_field(H)
        for config in PIXEL_SIZE_CONFIGS:
            x_sizes, y_sizes = _make_sizes(binary, config)
            p, a, h, w = objscale.get_structure_props(binary, x_sizes, y_sizes)
            p_sorted, a_sorted = _sort_props(p, a)
            path = os.path.join(REFERENCE_DIR, f'props_H{H}_{config}.npz')
            np.savez(path, perimeters=p_sorted, areas=a_sorted)
            print(f"  H={H}, {config}: {len(a)} structures -> {os.path.basename(path)}")

    for H in [0.3, 0.7]:
        binary = _generate_field(H, pad=False)  # no zero-pad: let truncation logic work
        for config in PIXEL_SIZE_CONFIGS:
            x_sizes, y_sizes = _make_sizes(binary, config)
            for variable in ['area', 'perimeter']:
                bins_mid, nontrunc, trunc, trunc_idx = objscale.finite_array_size_distribution(
                    binary, variable=variable, x_sizes=x_sizes, y_sizes=y_sizes,
                    bins=100, min_threshold=2,
                )
                path = os.path.join(REFERENCE_DIR, f'sizedist_{variable}_H{H}_{config}.npz')
                np.savez(path, bins_mid=bins_mid, nontrunc=nontrunc,
                         trunc=trunc, trunc_idx=trunc_idx)
                print(f"  H={H}, {config}, {variable} -> {os.path.basename(path)}")

    print("Reference data generation complete.")


# =============================================================================
# Tests
# =============================================================================

def test_fbm_spot_check():
    """
    Verify that scaleinvariance.fBm_ND_circulant produces the expected values.

    If this fails, the fBm generator itself has changed. All downstream test
    failures should be attributed to scaleinvariance, not objscale.
    """
    print("\n=== Test: fBm spot-check ===")
    failures = []

    for H in H_VALUES:
        field = _generate_raw_field(H)
        expected = FBM_SPOT_VALUES[H]
        for k, (i, j) in enumerate(FBM_SPOT_PIXEL_LOCS):
            actual = float(field[i, j])
            if abs(actual - expected[k]) > ATOL:
                failures.append(f"H={H}, pixel ({i},{j}): expected {expected[k]}, got {actual}")

    if failures:
        for f in failures:
            print(f"  FAIL  {f}")
        raise AssertionError(
            f"fBm spot-check failed ({len(failures)} mismatches). "
            "scaleinvariance.fBm_ND_circulant may have changed — "
            "regenerate reference data with --regen if the new values are correct."
        )
    print(f"  PASS  All {len(H_VALUES) * len(FBM_SPOT_PIXEL_LOCS)} spot values match")


def test_fractal_exact_props():
    """
    Verify get_structure_props returns analytically exact values for recursive fractals.

    All structures are perfect squares, so area, perimeter, height, width, and
    count per scale class are exactly known. No tolerance needed.
    """
    print("\n=== Test: fractal exact structure properties ===")
    failures = []

    for seed_name, iter_dict in FRACTAL_EXACT.items():
        for iterations, expected_groups in iter_dict.items():
            fractal = generate_fractal(seed=seed_name, iterations=iterations)
            binary = objscale.encase_in_value(fractal.astype(np.float32), value=0, dtype=np.float32)
            x_sizes = np.ones_like(binary, dtype=np.float32)
            y_sizes = np.ones_like(binary, dtype=np.float32)

            p, a, h, w = objscale.get_structure_props(binary, x_sizes, y_sizes)
            label = f"{seed_name}/iter={iterations}"

            # Check total structure count
            expected_total = sum(eg[4] for eg in expected_groups)
            if len(a) != expected_total:
                failures.append(f"{label}: expected {expected_total} structures, got {len(a)}")
                continue

            # Check each scale class
            for exp_a, exp_p, exp_h, exp_w, exp_count in expected_groups:
                mask = a == exp_a
                count = np.sum(mask)
                if count != exp_count:
                    failures.append(f"{label}: area={exp_a}, expected count={exp_count}, got {count}")
                    continue

                # All structures of this size should have identical properties
                for prop_name, prop_arr, exp_val in [
                    ('perimeter', p, exp_p), ('height', h, exp_h), ('width', w, exp_w),
                ]:
                    vals = prop_arr[mask]
                    if not np.all(vals == exp_val):
                        failures.append(
                            f"{label}: area={exp_a}, {prop_name} expected {exp_val}, "
                            f"got {np.unique(vals)}"
                        )

            if label not in str(failures):
                print(f"  PASS  {label} ({len(a)} structures, {len(expected_groups)} scale classes)")

    if failures:
        for f in failures:
            print(f"  FAIL  {f}")
        raise AssertionError(f"Fractal exact props: {len(failures)} failure(s)")
    print("  All fractal exact tests passed.")


def test_structure_props_regression():
    """
    Verify get_structure_props on seeded fBm fields matches saved reference data.

    Outputs are sorted by (area, perimeter) before comparison so that structure
    ordering does not matter.
    """
    print("\n=== Test: get_structure_props regression ===")
    failures = []

    for H in H_VALUES:
        binary = _generate_field(H)
        for config in PIXEL_SIZE_CONFIGS:
            x_sizes, y_sizes = _make_sizes(binary, config)
            p, a, h, w = objscale.get_structure_props(binary, x_sizes, y_sizes)
            p_sorted, a_sorted = _sort_props(p, a)

            ref_path = os.path.join(REFERENCE_DIR, f'props_H{H}_{config}.npz')
            if not os.path.exists(ref_path):
                raise FileNotFoundError(
                    f"Reference not found: {ref_path}\nRun with --regen first."
                )
            ref = np.load(ref_path)
            label = f"H={H}/{config}"

            if len(a_sorted) != len(ref['areas']):
                failures.append(f"{label}: count {len(a_sorted)} != ref {len(ref['areas'])}")
                continue

            for prop_name, current, ref_key in [
                ('areas', a_sorted, 'areas'),
                ('perimeters', p_sorted, 'perimeters'),
            ]:
                if not np.allclose(current, ref[ref_key], rtol=RTOL, atol=ATOL):
                    diffs = ~np.isclose(current, ref[ref_key], rtol=RTOL, atol=ATOL)
                    max_diff = np.max(np.abs(current - ref[ref_key]))
                    failures.append(
                        f"{label}/{prop_name}: {np.sum(diffs)} values differ, "
                        f"max diff={max_diff:.6e}"
                    )
                else:
                    print(f"  PASS  {label}/{prop_name} ({len(current)} structures)")

    if failures:
        for f in failures:
            print(f"  FAIL  {f}")
        raise AssertionError(f"Structure props regression: {len(failures)} failure(s)")
    print("  All structure props regression tests passed.")


def test_size_distribution_regression():
    """
    Verify finite_array_size_distribution on seeded fBm fields matches saved references.
    """
    print("\n=== Test: size distribution regression ===")
    failures = []

    for H in [0.3, 0.7]:
        binary = _generate_field(H, pad=False)  # no zero-pad: test truncation path
        for config in PIXEL_SIZE_CONFIGS:
            x_sizes, y_sizes = _make_sizes(binary, config)
            for variable in ['area', 'perimeter']:
                bins_mid, nontrunc, trunc, trunc_idx = objscale.finite_array_size_distribution(
                    binary, variable=variable, x_sizes=x_sizes, y_sizes=y_sizes,
                    bins=100, min_threshold=2,
                )

                ref_path = os.path.join(
                    REFERENCE_DIR, f'sizedist_{variable}_H{H}_{config}.npz'
                )
                if not os.path.exists(ref_path):
                    raise FileNotFoundError(
                        f"Reference not found: {ref_path}\nRun with --regen first."
                    )
                ref = np.load(ref_path)
                label = f"H={H}/{config}/{variable}"

                for arr_name, current, ref_key in [
                    ('bins_mid', bins_mid, 'bins_mid'),
                    ('nontrunc', nontrunc, 'nontrunc'),
                    ('trunc', trunc, 'trunc'),
                    ('trunc_idx', np.array(trunc_idx), 'trunc_idx'),
                ]:
                    cur = current.astype(float)
                    ref_arr = ref[ref_key].astype(float)
                    if not np.allclose(cur, ref_arr, rtol=RTOL, atol=ATOL):
                        max_diff = np.max(np.abs(cur - ref_arr))
                        failures.append(f"{label}/{arr_name}: max diff={max_diff:.6e}")

                if label not in str(failures):
                    print(f"  PASS  {label}")

    if failures:
        for f in failures:
            print(f"  FAIL  {f}")
        raise AssertionError(f"Size distribution regression: {len(failures)} failure(s)")
    print("  All size distribution regression tests passed.")


# =============================================================================
# Main
# =============================================================================

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Regression tests for get_structure_props refactor."
    )
    parser.add_argument('--regen', action='store_true',
                        help='Regenerate reference data (run this once before testing)')
    args = parser.parse_args()

    if args.regen:
        generate_reference_data()
        sys.exit(0)

    if not os.path.exists(REFERENCE_DIR):
        print("No reference data found. Generating...")
        generate_reference_data()

    passed = 0
    failed = 0
    tests = [
        test_fbm_spot_check,
        test_fractal_exact_props,
        test_structure_props_regression,
        test_size_distribution_regression,
    ]
    for test_func in tests:
        try:
            test_func()
            passed += 1
        except AssertionError as e:
            print(f"\n*** {e}")
            failed += 1
        except Exception as e:
            print(f"\n*** ERROR in {test_func.__name__}: {e}")
            failed += 1

    print(f"\n{'=' * 60}")
    print(f"SUMMARY: {passed} passed, {failed} failed")
    print(f"{'=' * 60}")
    sys.exit(0 if failed == 0 else 1)
